name: Create Doxygen
on:
  push:
    branches:
      - 'Documentation'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.5
